//appspec.yml

version: 0.0  
os: linux  
files:  
  - source: /  
    destination: /home/ubuntu/airbnbrepoforcloud9  
hooks:  
  ApplicationStart:  
    - location: scripts/start_server.sh  
      timeout: 300